### ISSUE TITLE
Support for https://www.mupload.nl/img/eyyhfiktwzqyb.jpeg

### ISSUE THREAD

**Issue by Sicos1977** [s9e/phpbb-ext-mediaembed#17]
Hi,

Is it possible to add support for this image provider?

Example link: https://www.mupload.nl/img/eyyhfiktwzqyb.jpeg

https://www.mupload.nl/

Greetings,
Kees van Spelde

**Comment by JoshyPHP** [comment]
No, simple images can be displayed with the `[img]` BBCode so it doesn't really add any value to the extension. If the goal is to automatically replace image links with the images themselves, then it would be better handled by a separate extension that dies that for any URL that looks like an image link, rather than limit it to a specific site.

You can request such an extension in [phpBB.com's Extension Requests forum](https://www.phpbb.com/community/viewforum.php?f=496) to see if anybody else is interested and if you're willing to sponsor its development I could look into it.
